---
# tasks file for web-server-role

- name: Enable amazon-linux-extras packages
  shell: amazon-linux-extras enable nginx1

- name: Install Nginx
  yum:
      name: nginx
      state: present

- name: index.html copy
  template: 
      src=index_template.j2 
      dest=/usr/share/nginx/html/index.html

- name: Start Nginx
  service:
      name: nginx
      enabled: true
      state: started
